### ISSUE TITLE
Update plugin to avoid Wordfence Alert

### ISSUE THREAD

**Issue by thomas-price** [Mahjouba91/multiple-roles#12]
Hi Florian,
Is there any chance an update to this great little plugin can be released here (https://wordpress.org/plugins/multiple-roles/) to stop the Wordfence alerts?
May be also modify readme.txt to include PHP version
```
=== Multiple Roles ===
…
Requires PHP: 7.2
…
```

many thanks

**Comment by Mahjouba91** [comment]
Hello @thomas-price,

Can you tell me what the Wordfence alert tell you?

**Comment by thomas-price** [comment]
I think these will be solved if you publish 1.3.1

The Plugin "Multiple Roles" appears to be abandoned (updated 22/08/2017, tested to WP 4.9.15).
Type: Plugin Abandoned
![image](https://user-images.githubusercontent.com/66541936/86236984-48660200-bbde-11ea-81e3-8b34a4ca8749.png)

Also on WordPress...
![image](https://user-images.githubusercontent.com/66541936/86237217-b4486a80-bbde-11ea-9c61-28e5f7f6f768.png)

**Comment by Mahjouba91** [comment]
All right. I see, let me find some time to drop a release to WordPress repo

**Comment by thomas-price** [comment]
Merci Florian
