### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by SCOMAC1959** [Mahjouba91/multiple-roles#13]
I'm trying to use a front end form (Gravity Forms) to assign User Roles (multiple) to a new User Registration. I'm using a plugin called User Role Editor to create the User Roles and this plugin to allow for multiple roles per user. I'm using _mu_add_roles_in_signup_meta_ within Gravity forms to try to assign the user roles for the user registration but it's not working. Any suggestions how I might be able to get this to work?

**Comment by chrneumann** [comment]
If this is still an issue, please reopen at: https://github.com/chrneumann/multiple-roles
