### ISSUE TITLE
Plus dans la liste des plugin WP

### ISSUE THREAD

**Issue by Leboubou111** [Mahjouba91/multiple-roles#14]
Bonjour @Mahjouba91 

Je vois que le plugin a été rejeté par WP pour des raisons de sécurités.

Un update à venir ?

**Comment by Mahjouba91** [comment]
Hello, oui ils me demandent encore des changements à faire, ils sont très pointilleux, ca demande du temps

**Comment by Leboubou111** [comment]
Cool, merci Florian ;-)

Ce plugin ajoute seulement une petite fonctionnalité, mais tellement indispensable pour laisser la main au client.
Merci pour ton temps au développement de ce dernier.

PS : ne peux tu pas faire `if ( is_admin() )` au début de `multiple-roles.php` afin qu'en front le code, les classes, filtres et actions ne soient pas chargé ?
J'ai testé, ca fonctionne correctement.

**Comment by Mahjouba91** [comment]
Merci pour ton retour,

Tu peux faire une pull request je pourrais regarder et merge ca

**Comment by Leboubou111** [comment]
PR envoyée. Merci pour tes efforts ;-)

#15

**Comment by David-COUDRAY** [comment]
Salut @Mahjouba91 

Je change de compte Github mais toujours la même personne.

Tu as des nouvelles quant à la remise du plugin sur le répertoire officiel WP ?

Pour l'instant je l'installe manuellement mais je pense que les plugins de sécu ne vont pas aimer très longtemps.

PS : J'ai testé HM Multiple Role qui reprend la même fonction mais des erreurs 404 sur certain user.

**Comment by Mahjouba91** [comment]
Hello @David-COUDRAY, je te cache pas que j'ai plus trop de motive à maintenir le plugin malheureusement, si ca te dis de forker ce serait peut etre mieux désolé

**Comment by David-COUDRAY** [comment]
Ok, je vais voir pour faire un fork... Ca sera mon premier plugin déposé sur le référentiel 

Pourrais-tu m'envoyer les modifications qu'ils t'ont demandé ?

**Comment by chrneumann** [comment]
The plugin is back online, I took over the maintenance: https://wordpress.org/plugins/multiple-roles/
