### ISSUE TITLE
Call to undefined function debug()

### ISSUE THREAD

**Issue by guicara** [Mahjouba91/multiple-roles#2]
Hello,

Just to inform you that when installing the plugin on my WordPress (v.4.7) I had an error exception.

> Call to undefined function debug()
> on multiple-roles\multiple-roles.php l.37

```
// For new user form (in Backoffice)
// In multisite, user_register hook is too early so wp_mu_activate_user add user role after
if ( is_multisite() ) {
//	add_filter( 'signup_user_meta',      array( $checklist, 'mu_add_roles_in_signup' ), 10, 4 ); // Waiting https://core.trac.wordpress.org/ticket/39223
	$bool = remove_action( 'wpmu_activate_user', 'add_new_user_to_blog', 10, 3 );
	debug( $bool );
	add_action( 'wpmu_activate_user',    array( $checklist, 'mu_add_roles_after_activation' ), 10, 3 );
} else {
	add_action( 'user_register',         array( $checklist, 'process_checklist' ) );
}
```

Removing the line `debug( $bool );` fix the issue.

Thanks,

Guillaume

**Comment by Mahjouba91** [comment]
Hey, thanks for your catch, I broked the package :/ 

It should be good now, you can download again the plugin

**Comment by guicara** [comment]
Hello Florian,

Thank you. But when I fetch your plugin through [WPackagist](https://wpackagist.org/search?q=multiple-roles&type=any&search=) (version 1.1.2) I have the old version. Do you know why?

**Comment by Mahjouba91** [comment]
Hum, could you check again please ?

In the doc, WPpackagist say : Scans the WordPress Subversion repository every hour for plugins and themes. Fetches the tags for each updated package and maps those to versions.

They should download the zip of the last version like this : https://downloads.wordpress.org/plugin/multiple-roles.1.1.2.zip
